### ISSUE TITLE
Single quotes for `kv.value` can cause errors with certain values

### ISSUE THREAD

**Issue by BrutalBirdie** [GzEvD/ansible-role-gitlab#2]
Example would be this setting:

```yaml
gitlab_extra_settings:
  - gitlab_rails:
    - key: "registry_key_path"
      value: "/etc/gitlab/registry.key"
  - registry:
    - key: "internal_key"
      value: "{{ gitlab_registry_internal_secret }}"
```
Where `gitlab_registry_internal_secret` is a RSA key like described in the doc:
https://docs.gitlab.com/ee/administration/packages/container_registry.html#use-an-external-container-registry-with-gitlab-as-an-auth-endpoint

```
# registry['internal_key'] should contain the contents of the custom key
# file. Line breaks in the key file should be marked using `\n` character
# Example:
registry['internal_key'] = "---BEGIN RSA PRIVATE KEY---\nMIIEpQIBAA\n"

# Optionally define a custom file for Omnibus GitLab to write the contents
# of registry['internal_key'] to.
gitlab_rails['registry_key_path'] = "/custom/path/to/registry-key.key"
```

With single quotes the key will be placed literal with the `\n` as string and not as line break in the keyfile.
Which leads to auth erros with the registry.

https://github.com/GzEvD/ansible-role-gitlab/blob/a1d6d83cf7ee146af2f16d1dd7154f957c971646/templates/gitlab.rb.j2#L132
